# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/nbdev-hello',
                'lib_path': 'nbdev_hello'},
  'syms': { 'nbdev_hello.book': { 'nbdev_hello.book.Book': ('book.html#book', 'nbdev_hello/book.py'),
                                  'nbdev_hello.book.Book._init': ('book.html#book._init', 'nbdev_hello/book.py'),
                                  'nbdev_hello.book.Book._str_': ('book.html#book._str_', 'nbdev_hello/book.py')},
            'nbdev_hello.core': {'nbdev_hello.core.foo': ('core.html#foo', 'nbdev_hello/core.py')}}}
