# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_book.ipynb.

# %% auto 0
__all__ = ['Book']

# %% ../nbs/01_book.ipynb 3
class Book:
    """Class representation of book"""
    
    def __init__(
        self,
        title, # title of the book
        author, # book's author
    ):
        self.title = title
        self.author = author
        
    def __str__(self):
        return f"'{title}', by {author}!"
    
